const AppName = 'Tagg';
export const EULAText = `
This End User License Agreement (“Agreement”) is between you and ${AppName} and governs use of this app made available through the Apple App Store. By installing the ${AppName} App, you agree to be bound by this Agreement and understand that there is no tolerance for objectionable content. If you do not agree with the terms and conditions of this Agreement, you are not entitled to use the ${AppName} App.<

In order to ensure ${AppName} provides the best experience possible for everyone, we strongly enforce a no tolerance policy for objectionable content. If you see inappropriate content, please use the "Report" feature found under the three dots menu of each post or user profile.

1. Parties This Agreement is between you and ${AppName} only, and not Apple, Inc. (“Apple”). Notwithstanding the foregoing, you acknowledge that Apple and its subsidiaries are third party beneficiaries of this Agreement and Apple has the right to enforce this Agreement against you. ${AppName}, not Apple, is solely responsible for the ${AppName} App and its content.

2. Privacy ${AppName} may collect and use information about your usage of the ${AppName} App, including certain types of information from and about your device. ${AppName} may use this information, as long as it is in a form that does not personally identify you, to measure the use and performance of the ${AppName} App.

3. Limited License ${AppName} grants you a limited, non-exclusive, non-transferable, revocable license to use the${AppName} App for your personal, non-commercial purposes. You may only use the${AppName} App on Apple devices that you own or control and as permitted by the App Store Terms of Service.

4. Age Restrictions By using the ${AppName} App, you represent and warrant that (a) you are 17 years of age or older and you agree to be bound by this Agreement; (b) if you are under 17 years of age, you have obtained verifiable consent from a parent or legal guardian; and (c) your use of the ${AppName} App does not violate any applicable law or regulation. Your access to the ${AppName} App may be terminated without warning if ${AppName} believes, in its sole discretion, that you are under the age of 17 years and have not obtained verifiable consent from a parent or legal guardian. If you are a parent or legal guardian and you provide your consent to your child's use of the ${AppName} App, you agree to be bound by this Agreement in respect to your child's use of the ${AppName} App.

5. Objectionable Content Policy Content may not be submitted to ${AppName}, who will moderate all content and ultimately decide whether or not to post a submission to the extent such content includes, is in conjunction with, or alongside any, Objectionable Content. Objectionable Content includes, but is not limited to: (i) sexually explicit materials; (ii) obscene, defamatory, libelous, slanderous, violent and/or unlawful content or profanity; (iii) content that infringes upon the rights of any third party, including copyright, trademark, privacy, publicity or other personal or proprietary right, or that is deceptive or fraudulent; (iv) content that promotes the use or sale of illegal or regulated substances, tobacco products, ammunition and/or firearms; and (v) gambling, including without limitation, any online casino, sports books, bingo or poker.

6. Warranty ${AppName} disclaims all warranties about the ${AppName} App to the fullest extent permitted by law. To the extent any warranty exists under law that cannot be disclaimed, ${AppName}, not Apple, shall be solely responsible for such warranty.

7. Maintenance and Support ${AppName} does provide minimal maintenance or support for it but not to the extent that any maintenance or support is required by applicable law, ${AppName}, not Apple, shall be obligated to furnish any such maintenance or support.

8. Product Claims ${AppName}, not Apple, is responsible for addressing any claims by you relating to the ${AppName} App or use of it, including, but not limited to: (i) any product liability claim; (ii) any claim that the ${AppName} App fails to conform to any applicable legal or regulatory requirement; and (iii) any claim arising under consumer protection or similar legislation. Nothing in this Agreement shall be deemed an admission that you may have such claims.

9. Third Party Intellectual Property Claims ${AppName} shall not be obligated to indemnify or defend you with respect to any third party claim arising out or relating to the ${AppName} App. To the extent ${AppName} is required to provide indemnification by applicable law, ${AppName}, not Apple, shall be solely responsible for the investigation, defense, settlement and discharge of any claim that the ${AppName} App or your use of it infringes any third party intellectual property right.
`;
