// import UserAPI from '../neo';

// const mockStore = {
//   user: {
//     findUser: jest.fn(),
//     // findOtherBids: jest.fn(),
//     getQueueMore: jest.fn(),
//     userHasDateOpen: jest.fn(),
//     userDistanceApart: jest.fn(),
//     userIsFollowing: jest.fn(),
//     getFollowersFromUser: jest.fn(),
//     findBidsFromUser: jest.fn(),
//     findDateRequests: jest.fn(),
//     getUserQueue: jest.fn(),
//     getMatchedDates: jest.fn(),
//     setUser: jest.fn(),
//     setUserQueue: jest.fn(),
//     createUser: jest.fn(),
//     followUser: jest.fn(),
//     unFollowUser: jest.fn(),
//     setUserFlag: jest.fn(),
//     setBlockUser: jest.fn(),
//   },
//   date: {
//     findDate: jest.fn(),
//     getDateCreator: jest.fn(),
//     findDateBidder: jest.fn(),
//     findDateFromBid: jest.fn(),
//     findCreatorFromDate: jest.fn(),
//     findNumberOfBidsFromDAte: jest.fn(),
//     findDateWinner: jest.fn(),
//     findBidsFromDate: jest.fn(),
//     createBid: jest.fn(),
//     createDate: jest.fn(),
//     createDateWinner: jest.fn(),
//   },
// };
