# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ManhattanMatch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

  # Pods for ManhattanMatch

  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  target 'ManhattanMatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ManhattanMatch-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ManhattanMatch-tvOS

  target 'ManhattanMatch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
